//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordFinderEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordFinderEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	&quot;aa&quot;,
        ///	&quot;aah&quot;,
        ///	&quot;aahed&quot;,
        ///	&quot;aahing&quot;,
        ///	&quot;aahs&quot;,
        ///	&quot;aal&quot;,
        ///	&quot;aalii&quot;,
        ///	&quot;aaliis&quot;,
        ///	&quot;aals&quot;,
        ///	&quot;aardvark&quot;,
        ///	&quot;aardvarks&quot;,
        ///	&quot;aardwolf&quot;,
        ///	&quot;aardwolves&quot;,
        ///	&quot;aargh&quot;,
        ///	&quot;aarrgh&quot;,
        ///	&quot;aarrghh&quot;,
        ///	&quot;aas&quot;,
        ///	&quot;aasvogel&quot;,
        ///	&quot;aasvogels&quot;,
        ///	&quot;ab&quot;,
        ///	&quot;aba&quot;,
        ///	&quot;abaca&quot;,
        ///	&quot;abacas&quot;,
        ///	&quot;abaci&quot;,
        ///	&quot;aback&quot;,
        ///	&quot;abacterial&quot;,
        ///	&quot;abacus&quot;,
        ///	&quot;abacuses&quot;,
        ///	&quot;abaft&quot;,
        ///	&quot;abaka&quot;,
        ///	&quot;abakas&quot;,
        ///	&quot;abalone&quot;,
        ///	&quot;abalones&quot;,
        ///	&quot;abamp&quot;,
        ///	&quot;abampere&quot;,
        ///	&quot;abamperes&quot;,
        ///	&quot;abamps&quot;,
        ///	&quot;abandon&quot;,
        ///	&quot;abandoned&quot;,
        ///	&quot;abandoner&quot;,
        ///	&quot;abandoners&quot;,
        ///	&quot;abando [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultDictionary {
            get {
                return ResourceManager.GetString("DefaultDictionary", resourceCulture);
            }
        }
    }
}
